language: php
notifications:
  email:
    - lixworth@gmail.com
php:
  - '7.3'

before_script:
  - chmod -R 777 ./tests/travis.sh
  - echo "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n" | pecl install swoole
  - echo "\r\n" | pecl install yaml
  - composer install

script:
  - ./build.sh
  - ./tests/travis.sh